### ISSUE TITLE
add python requirements

### ISSUE THREAD

**Issue by zpeters** [pirate/bookmark-archiver#102]
uses requirements.txt (or some other method) to specify which python libs are needed.  For example "requests" is needed but i didn't see in setup that it is ever checked/installed

**Comment by pirate** [comment]
For some reason I keep forgetting to add this, I guess because I assume everyone already has `requests` installed.

I might actually remove the `requests` dependency in favor of using the standard library, since we only use it in one place anyway.

**Comment by pirate** [comment]
done
