### ISSUE TITLE
Archive Method: Add support for .webarchive output

### ISSUE THREAD

**Issue by rcarmo** [pirate/bookmark-archiver#11]
Just to let you know that I published a sample on how to create Safari `.webarchive` files: https://github.com/rcarmo/python-webarchive - might be useful, since it also provides a sample Python 3 `asyncio` crawler :)

**Comment by pirate** [comment]
:+1: thanks! I'm also checking out https://github.com/chfoo/wpull for warc support.

**Comment by rcarmo** [comment]
Nice - will see if I can do something with it!

**Comment by pirate** [comment]
Apparently wget supports saving to warc files!

```bash
‘--warc-file=file’
Use file as the destination WARC file.
```
https://www.gnu.org/software/wget/manual/wget.html

**Comment by rcarmo** [comment]
Yep. Different format, though.

**Comment by pirate** [comment]
I've decided to close this for now, since WARC is more officially supported and .webarchive is safari-only, I don't think it's worth investing time into this before WARC generation and replay is finished.
