### ISSUE TITLE
Automatically fetch new links via Pocket API/RSS

### ISSUE THREAD

**Issue by pirate** [pirate/bookmark-archiver#2]
Read Pocket API key from argv, and use it to fetch an updated link stream.

```bash
./archive.py --api 3409812nkln4l32k897ds098v  # api token
```

**Comment by stephanepechard** [comment]
There are 3 different Pocket APIs (see https://getpocket.com/developer/docs/overview). I think the tool should be able to run a complete synchronisation of the user account using them (I don't say it's easy :-) ).

**Comment by pirate** [comment]
Actually I think scraping the pocket RSS feed is easier than setting up API keys: https://getpocket.com/users/nikisweeting/feed/all

**Comment by pirate** [comment]
Done! https://github.com/pirate/bookmark-archiver/releases/tag/v0.0.3
