### ISSUE TITLE
Consider removing 'star' / 'starred' from repo description, docs, and template

### ISSUE THREAD

**Issue by bardisty** [pirate/bookmark-archiver#34]
Just a minor suggestion, as the use of the word `star` may confuse some users who stumble upon the project. Main reason being, Bookmark Archiver supports a wide array of different bookmark formats/services, where most of them don't use the term `star` for anything, or if they do it might be used differently. Pinboard is one such case, where you can star any of your bookmarks and view all your starred bookmarks in one place:

![screenshot-1499250869_1652x780](https://user-images.githubusercontent.com/6248459/27860798-f4503a04-6132-11e7-862f-33e9caa6e074.png)

The way the project reads currently, one might think it only includes "starred bookmarks". Instead of `star`, perhaps simply `bookmark` is a better choice:

```diff
- Save an archived copy of all websites you star (the actual content of the sites, not just the list of bookmarks).
+ Save an archived copy of all websites you bookmark (the actual content of the sites, not just the list of bookmarks).
```

As for the template, `Starred` could be replaced with `Bookmarked` or `Date`; both are equally clear to me.

**Comment by pirate** [comment]
You "Star" a site in the address bar to bookmark it in chrome as well, that's why I thought the language was fairly clear.  Seems like that's not the case though, so I'll change it.

**Comment by pirate** [comment]
Done: 4db3077
