### ISSUE TITLE
Set User-Agent of Wget to Chrome or Custom Value

### ISSUE THREAD

**Issue by tscs37** [pirate/bookmark-archiver#35]
Some websites do not properly permit wget to crawl the entire site, they block with a 403 or empty webpages.

For this it would be useful to set the `--user-agent` parameter of wget to another value.

A good default would be the chrome user-agent, which would make websites show as-in-browser instead of how they treat wget's default.

Alternatively the User-Agent `Lynx` can be used, websites that are aware of Lynx will reduce JS and CSS contents, making it easier to archive the page.

**Comment by pirate** [comment]
I thought about this actually, and I'd rather respect site's desires to not be crawled unless explicitly overridden.

I'm happy adding a user agent change, but I want to stick it behind a configuration variable like `WGET_USER_AGENT` or something, and leave the default as `wget`.  If people want to change it they can.

**Comment by pirate** [comment]
Done: acf59fa
