### ISSUE TITLE
Index: Add a way to sort the index table by column

### ISSUE THREAD

**Issue by nodiscc** [pirate/bookmark-archiver#40]
Currently, archived items on the index page are sorted by reverse chronological order (most recent first), most likely they are presented in the same order as the original HTML bookmarks export.

It would be nice to be able to sort the table by clicking on each column's header. Eg.

 * Sort items by reverse/chronological order
 * Sort items by title
 * Sort items by original URL

This would probably require a bit of Javascript

**Comment by pirate** [comment]
I can sort of see the appeal of chronological order, but what's the use case for sorting by Title/URL?

**Comment by nodiscc** [comment]
Sorting by URL would be nice to group articles by website, even if they have been bookmarked months apart. As you said in #41 Ctrl+F works, but is less practical.

Enabling JS should be fully optional and the index page should still work with js disabled.

**Comment by pirate** [comment]
Cool, that's a pretty good use case, I didn't think of that.  I'll keep this open until I have some time to hack on it.

**Comment by pirate** [comment]
Woah guys I just found this https://github.com/jlord/sheetsee-pocket ([DEMO](http://jlord.us/sheetsee-pocket/)), it looks awesome, and has a bunch of cool features!

I pinged @jlord to see if she's interested in working on bookmark-archiver, but if not I still plan on borrowing some inspiration from her cool index design, including sortable columns and clickable tags.

**Comment by jlord** [comment]
Hi @pirate! Sorry about the delay! I don't have any bandwidth to help unfortunately but feel free to take inspiration! ✨
