### ISSUE TITLE
Add a way to filter the index table (by typing text)

### ISSUE THREAD

**Issue by nodiscc** [pirate/bookmark-archiver#41]
Similar to https://github.com/pirate/bookmark-archiver/issues/40,

I'd like to be able to filter the index table by typing text in a `Filter...` text field. Eg. when typing `github` in the filtering field, only display items containing `github` in their title (or URL?)

 * Consider actually starting the filtering _after_ the 2nd or 3rd character has been entered (to improve performance, plus filtering on a single character does not make much sense). Alternatively, only filter after the user hits `Enter` or a similar `Go` button.
 * Consider adding a `clear` button to clear the current filter text.

This would probably require a bit of Javascript. I found a rather efficient filtering script https://github.com/nodiscc/awesome-selfhosted/blob/yaml/html/filtering.js which I was planning to use for another project but it might as well serve here.

Note: This is different from full text search (probably easier to achieve) and only relates to the main `index.html` archive index

**Comment by pirate** [comment]
Ctrl+F

**Comment by nodiscc** [comment]
Sometime I'd like to _only_ see the items relevant to a particular search. Ctrl+F is nice but doesn't do what I need. Anyway thanks for replying
