### ISSUE TITLE
search.py: how to use it, description in readme?

### ISSUE THREAD

**Issue by zaszlo** [pirate/bookmark-archiver#46]
From the issues I've found out about the recommended search.py way of searching in the archive. I Have set the archive path.

For some search terms I get this exception but for others it just works as expected.
Maybe I'm not doing something right?

./search.py "church"
Traceback (most recent call last):
  File "./search.py", line 66, in <module>
    print('\n'.join(matches))
  File "./search.py", line 16, in <genexpr>
    return (l.decode().replace(archive_path, '') for l in ag.stdout.splitlines())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 75: invalid continuation byte

If I add the --exact parameter to it, it will not yield the exception but also no results are given.

**Comment by pirate** [comment]
`search.py` isn't finished yet, for now you can run the search command directly:

https://geoff.greer.fm/ag/

```bash
brew install the_silver_searcher
# OR
apt-get install silversearcher-ag
```

Then 
```bash
cd ~/path/to/archive
ag 'search-term.*with-regex'
ag -Q 'exact-search-term'
```
