### ISSUE TITLE
links generated with incorrect folder

### ISSUE THREAD

**Issue by danhimalplanet** [pirate/bookmark-archiver#67]
I have a simple bookmark export file containing 1 url

https://gist.github.com/danhimalplanet/444a7bc30b34d249d4429527c78f5792

➜  ./archive.py ~/Downloads/bookmarks_1_30_18.html 2>&1 >/dev/null
➜  echo $?
0

this generates 'html/archive/index.html' https://gist.github.com/danhimalplanet/ac212bc2cd0047807ede39ba20934330

the generated index.html has relative links like:

'html/archive/archive/1517380882/screenshot.png'

the screenshot relative link is:

'html/archive/archive/1517380882/screenshot.png'

There is an extra 'archive' in the 2 links.

I can make this work if I symlink a directory 'archive' in 'html/archive' to point 1 directory up from 'html/archive'.  That seems like a hack, or I'm doing something wrong.

**Comment by pirate** [comment]
Thanks for reporting this, I'm probably just doing a bad path concatenation somewhere, thanks for reporting this!

**Comment by InconsolableCellist** [comment]
I have the same issue. The files generate properly but they're linked improperly, though it doesn't affect the PDF and screenshot links. I also see a png file that has a .png.html extension in the link

**Comment by InconsolableCellist** [comment]
As a workaround to the ./archive problem I made a symlink in the local dir to ./archive, but this only seems to work some of the time, maybe? I didn't dig deep yet, there were a few issues I was having at once.

**Comment by pirate** [comment]
Found and fixed as of: 1776bdf

Please pull and let me know if it works!

(Make sure to back up your archive beforehand in case anything gets messed up, this is still BETA code)
