### ISSUE TITLE
Permissions are not applied to PDF output

### ISSUE THREAD

**Issue by cdzombak** [pirate/bookmark-archiver#73]
I'm running `archiver.py` without passing `ARCHIVE_PERMISSIONS`, which _should_ result in permissions of `755`per [the README](https://github.com/pirate/bookmark-archiver#configuration).

This seems to work as expected _except_ for the PDFs in the output. They appear to be created with permissions `600`. Here's an example listing from my archive:

```
$ ls -l html/archive/1520809520
total 480
-rwxr-xr-x  1 cdzombak  staff   492B Mar 13 20:35 favicon.ico*
-rwxr-xr-x  1 cdzombak  staff    11K Mar 13 22:00 index.html*
-rwxr-xr-x  1 cdzombak  staff   3.5K Mar 13 22:00 index.json*
-rw-------@ 1 cdzombak  staff    70K Mar 13 20:35 output.pdf
-rwxr-xr-x@ 1 cdzombak  staff   144K Mar 13 20:35 screenshot.png*
drwxr-xr-x  3 cdzombak  staff    96B Mar 13 20:35 www.proporti.onl/
```

As a workaround, the script I'm running via cron runs `archive.py` then:

```sh
find /path/to/bookmark-archiver/html -name "*.pdf" -exec chmod 755 {} \;
```

**Comment by pirate** [comment]
Good catch, fixed in dc9445b.
