### ISSUE TITLE
موسسة بن معلاق

### ISSUE THREAD

**Issue by aseeralmeem** [pirate/bookmark-archiver#77]
➜ ~/D/C/bookmark-archiver py[archiver] ⎇ (ssl-check) ./archive.py "https://medium.com/feed/@thesquashsh"
[*] [2018-01-12 12:23:50] Downloading https://medium.com/feed/@thesquashsh > downloads/medium.com.txt
[X] No links found :(
[1]

**Comment by pirate** [comment]
Duplicate of https://github.com/pirate/bookmark-archiver/issues/64
