### ISSUE TITLE
Tried to run on a Raspberry Pi...

### ISSUE THREAD

**Issue by will76** [pirate/bookmark-archiver#78]
I'm getting this message:
```
./archive http://www.example/feeds/global.xml
  File "./archive", line 63
    **ANSI,
          ^
SyntaxError: invalid syntax
```
python3 shows:
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux

Anyone running successfully??

**Comment by pirate** [comment]
Upgrade your python, it needs at least 3.5.
