### ISSUE TITLE
Suggestion: add 'web-archiving' tag to project.

### ISSUE THREAD

**Issue by issmirnov** [pirate/bookmark-archiver#81]
I recently stumbled upon a series of projects that all share the tag [web-archiving](https://github.com/topics/web-archiving) here on github. This project was harder to find. If the author is interested in increasing visibility, adding the tag should help.

Thanks for making this awesome tool!

**Comment by pirate** [comment]
Done, thx!

**Comment by issmirnov** [comment]
Sweet, thanks!
