### ISSUE TITLE
Request: Following redirect URLs

### ISSUE THREAD

**Issue by W1lkins** [pirate/bookmark-archiver#83]
Some of my pocket bookmarks are saved as `t.co` URLs from Twitter. So it's pretty difficult to find out what these URLs are at first glance without visiting them.

Would it be worth us making a `HEAD` request to the URL, checking for a redirect, and a "Location" header, then working with the forwarded URL instead?

I can probably tackle this problem if desired

**Comment by pirate** [comment]
Did you figure out a solution to this on your own? I'm curious as to how you ended up solving it.

**Comment by W1lkins** [comment]
Not as of yet, I have a hacky solution - but I was planning on implementing it properly and making a PR.

Not sure if many people encounter the same problem/it's worth solving though, hence the close.
